#!/bin/sh
export LIBSEAT_BACKEND=seatd
export LIBVA_DRIVER_NAME=iHD
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export WLR_NO_HARDWARE_CURSORS=0
export WLR_RENDERER=vulkan
export XDG_CURRENT_SESSION=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export __GL_SYNC_TO_VBLANK=0
export vblank_mode=0

exec dbus-run-session sway "$@"
